//! T1 walking-skeleton check: spawn the bundled sidecar, cut one hardcoded cue to `.m4a`,
//! write one row, and hand the clip to the renderer to load through the asset protocol.
//!
//! Everything happens in a scratch folder under the OS temp dir with its own throwaway
//! database, so this never touches — or adds a table to — a real library (schema v1 is T4's).
//!
//! Headless use (CI, T21): launch the packaged binary with `--smoke`. The renderer runs the
//! check, loads the clip, and calls `smoke_finish`; the process prints one `SMOKE OK|FAIL`
//! line, optionally writes it to `--smoke-report <path>`, and exits 0 or 1. A watchdog exits
//! with 2 if the renderer never reports.

use std::path::PathBuf;
use std::time::Duration;

use serde::Serialize;
use tauri::{AppHandle, Manager};

use crate::error::{CommandError, CommandResult};
use crate::media::{self, ffmpeg};
use crate::store;

/// The hardcoded cue: 1.000 s → 3.000 s of a generated 5 s source.
const CUE_START_MS: u64 = 1_000;
const CUE_END_MS: u64 = 3_000;
const WATCHDOG: Duration = Duration::from_secs(90);

#[derive(Debug, Clone, Default)]
pub struct SmokeMode {
    pub enabled: bool,
    pub report_path: Option<PathBuf>,
}

impl SmokeMode {
    pub fn from_args() -> Self {
        let args: Vec<String> = std::env::args().collect();
        let report_path = args
            .iter()
            .position(|a| a == "--smoke-report")
            .and_then(|i| args.get(i + 1))
            .map(PathBuf::from);
        Self {
            enabled: args.iter().any(|a| a == "--smoke"),
            report_path,
        }
    }

    pub fn arm_watchdog(&self) {
        if !self.enabled {
            return;
        }
        let report_path = self.report_path.clone();
        std::thread::spawn(move || {
            std::thread::sleep(WATCHDOG);
            emit_result(&report_path, "FAIL watchdog: renderer never reported");
            std::process::exit(2);
        });
    }
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SmokeReport {
    pub clip_path: PathBuf,
    pub clip_bytes: u64,
    pub row_id: i64,
    pub cut_ms: u128,
}

fn io(e: std::io::Error) -> CommandError {
    CommandError::new("Smoke.Io", e)
}

#[tauri::command]
pub fn smoke_mode(mode: tauri::State<'_, SmokeMode>) -> bool {
    mode.enabled
}

#[tauri::command]
pub async fn run_smoke(app: AppHandle) -> CommandResult<SmokeReport> {
    let dir = std::env::temp_dir().join("DialogueCollector-smoke");
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).map_err(io)?;

    // 1. A source with a video and an audio stream, generated by the sidecar itself.
    let source = dir.join("source.mkv");
    let generate: Vec<String> = [
        "-hide_banner",
        "-nostdin",
        "-v",
        "error",
        "-f",
        "lavfi",
        "-i",
        "sine=frequency=440:duration=5",
        "-f",
        "lavfi",
        "-i",
        "color=c=black:s=320x240:d=5",
        "-c:a",
        "aac",
        "-c:v",
        "mpeg4",
        "-shortest",
        "-y",
    ]
    .into_iter()
    .map(str::to_owned)
    .chain([source.to_string_lossy().into_owned()])
    .collect();
    ffmpeg::run(&app, &generate).await?;

    // 2. Cut the hardcoded cue.
    let clip = dir.join(media::new_clip_filename());
    let cut = ffmpeg::cut_cue(&app, &source, CUE_START_MS, CUE_END_MS, &clip).await?;
    let clip_bytes = std::fs::metadata(&clip).map_err(io)?.len();

    // 3. One character and one line in a throwaway database with the real schema.
    let conn = store::open(&dir.join("smoke.sqlite"))?;
    let file_name = clip.file_name().unwrap().to_string_lossy().into_owned();
    let now = store::now_ms();
    conn.execute(
        "INSERT INTO characters (name, category, source, created_at, updated_at)
         VALUES ('Smoke', 'anime', 'T1', ?1, ?1)",
        [now],
    )
    .map_err(store::StoreError::from)?;
    let character_id = conn.last_insert_rowid();
    conn.execute(
        "INSERT INTO lines (character_id, text, audio_filename, audio_bytes, duration_ms, created_at, updated_at)
         VALUES (?1, 'smoke', ?2, ?3, ?4, ?5, ?5)",
        (
            character_id,
            &file_name,
            clip_bytes as i64,
            (CUE_END_MS - CUE_START_MS) as i64,
            now,
        ),
    )
    .map_err(store::StoreError::from)?;
    let row_id = conn.last_insert_rowid();

    // 4. Grant the asset protocol this folder at runtime, as library-open will (B11).
    app.asset_protocol_scope()
        .allow_directory(&dir, false)
        .map_err(|e| CommandError::new("Smoke.AssetScope", e))?;

    log::info!("smoke: cut {file_name} ({clip_bytes} bytes) in {cut:?}, row {row_id}");
    Ok(SmokeReport {
        clip_path: clip,
        clip_bytes,
        row_id,
        cut_ms: cut.as_millis(),
    })
}

/// Called by the renderer in `--smoke` mode once it has loaded (or failed to load) the clip.
#[tauri::command]
pub fn smoke_finish(mode: tauri::State<'_, SmokeMode>, ok: bool, detail: String) {
    if !mode.enabled {
        return;
    }
    let line = format!("{} {detail}", if ok { "OK" } else { "FAIL" });
    emit_result(&mode.report_path, &line);
    // Exit the process directly: Tauri 2 does not carry the code passed to
    // `AppHandle::exit` through to the process exit status, and CI reads that status.
    std::process::exit(if ok { 0 } else { 1 });
}

fn emit_result(report_path: &Option<PathBuf>, line: &str) {
    println!("SMOKE {line}");
    log::info!("SMOKE {line}");
    if let Some(path) = report_path {
        if let Err(e) = std::fs::write(path, format!("SMOKE {line}\n")) {
            log::error!("cannot write smoke report to {}: {e}", path.display());
        }
    }
}
